early_stopping_callback:
  min_delta: 0.0
  mode: min
  monitor: val_loss
  patience: 30
  verbose: false
matmul_precision: medium
meta:
  author: Marko Cvjetko
  checkpoint_path: results_21/mobilenetv3-step=266-epoch=00-val_loss=0.3573.ckpt
  job_type: debug
  logging: wandb
  project_name: DeepSniff-2.0.
  resume_from_checkpoint: false
model_checkpoint_callback:
  dirpath: models/train/annotated/default_train_3d_conv
  every_n_train_steps: null
  monitor: val_loss
  save_on_train_epoch_end: false
  save_top_k: 20
trainer:
  accelerator: gpu
  accumulate_grad_batches: 10
  check_val_every_n_epoch: 1
  devices:
  - 0
  enable_checkpointing: true
  enable_progress_bar: true
  log_every_n_steps: 10
  max_epochs: 50
  precision: '32'
wandb:
  group: default_train_classification
  job_type: training
  name: train/annotated/default_train_3d_conv
